from setuptools import setup, find_packages

setup(
    name='harmonai-tools',
    version='1.0.0',
    url='https://github.com/Harmonai-org/harmonai-tools.git',
    author='Harmonai',
    packages=find_packages(),    
    install_requires=[
        'aeiou',
        'audio-diffusion-pytorch @ https://github.com/Harmonai-org/audio-diffusion-pytorch/@main#egg=audio-diffusion-pytorch',
        'audio-metadata',
        'auraloss',
        'einops',
        'ema-pytorch',
        'encodec',
        'k-diffusion',
        'nwt-pytorch',
        'pandas',
        'pedalboard',
        'prefigure',
        'pytorch_lightning==1.7.4', 
        'PyWavelets',
        'sentencepiece',
        'torch',
        'torchaudio',
        'tqdm',
        'transformers',
        'v-diffusion-pytorch',
        'vector-quantize-pytorch',
        'wandb',
        'webdataset',
    ],
)